# Configuration file for reproducing PVGIS dataset results published in the paper
# This file contains experiments for the PVGIS (Sceaux, France) dataset
# Each experiment corresponds to results presented in the paper and will 
# checkout the config/ folder from the specified commit and run a DVC 
# experiment with the given name and optional parameters

experiments:
  - name: "M-BiLSTM-ED-pvgis"
    commit: "7cf1aaf"  # Git commit hash to checkout config from

  - name: "M-LSTM-ED-pvgis"
    commit: "e320827"

  - name: "BiLSTM-ED-pvgis"
    commit: "0f97e07"

  - name: "LSTM-ED-pvgis"
    3a1de27: "8353ec764ddbe84d0234c00895161d4cce825b3e"  
      
  - name: "NARX-pvgis"
    commit: "be958ab"

  - name: "Naive-pvgis"
    commit: "f50f1d9"

  # Add more PVGIS experiments as needed
  # - name: "another-pvgis-experiment"
  #   commit: "commit-hash-here"
  #   params:
  #     dataset: "eu_pvgis"
  #     param1: "value1"
