# Configuration file for reproducing SIAS dataset results published in the paper
# This file contains experiments for the SIAS (Palermo, Italy) dataset
# Each experiment corresponds to results presented in the paper and will 
# checkout the config/ folder from the specified commit and run a DVC 
# experiment with the given name and optional parameters

experiments:
  - name: "M-BiLSTM-ED-sias"
    commit: "9d01318"  # Git commit hash to checkout config from

  - name: "M-LSTM-ED-sias"
    commit: "5b760c2"

  - name: "BiLSTM-ED-sias"
    commit: "22facf1"

  - name: "LSTM-ED-sias"
    commit: "59d772d"  
      
  - name: "NARX-sias"
    commit: "d114e9c"

  - name: "Naive-sias"
    commit: "025f4d6"

  # Add more SIAS experiments as needed
  # - name: "another-sias-experiment"
  #   commit: "commit-hash-here"
  #   params:
  #     dataset: "sias_palermo"
  #     param1: "value1"
