base:
  data_dir: data/
  model_dir: trained_models/
  random_seed: 510
calc_daily_stats:
  latitude: 38
  noise_std:
  - 1.5
  - 0.1
  noise_dataset_selection:
  - 0
  - 1
  - 1
eval:
  eval_on_validation_set: false
  plot_dir: results_plot
  seasonality: 24
dataset:
  data_filename: EUPVGIS_sceaux_2006-2016.csv
  preprocess:
    split_method: datetimes
    split_dates:
    - 01/01/2013
    - 01/01/2014
    num_fourier_terms: 1
    discard_test_year_not_full: true
  parameters:
    dataset_type: pvgis
    rename_columns:
      G(i): radiance
      T2m: temperature
train:
  model:
    name: Lstm
    label_columns:
    - radiance
    past_exogenous_columns:
    - temperature
    future_exogenous_columns: null
    model_params:
      lstm_units:
      - 16
      dense_units:
      - 168
      num_features: 1
      use_bidirectional: true
      dropout: 1.763516190129362e-07
      out_steps: 24
      output_activation_function: linear
      output_kernel_initializer: glorot_uniform
      dense_activation: relu
      dense_kernel_initializer: he_uniform
      dense_bias_initializer: zeros
      dense_kernel_regularizer:
        module: keras.regularizers
        class_name: L1L2
        config:
          l1: 0.007701180752808035
          l2: 0.09101248057486648
      dense_bias_regularizer:
        module: keras.regularizers
        class_name: L1L2
        config:
          l1: 0.018652483037886646
          l2: 0.021403215111720178
  next_period_stats:
    next_period_stats:
      use_next_period_stats: false
  batch_size: 512
  output_window_size: 24
  input_window_size: 24
  window_shift: 1
  shuffle: true
  shuffle_buffer_size: 44000
  epochs: 40
  early_stopping: false
  loss:
    name: MeanSquaredError
  optimizer_params:
    learning_rate:
      name: ExponentialDecay
      initial_learning_rate: 0.002952384903462967
      decay_steps: 120
      decay_rate: 0.9383768365181983
      staircase: false
