base:
  data_dir: data/
  model_dir: trained_models/
  random_seed: 510
calc_daily_stats:
  latitude: 38
  noise_std:
  - 1.5
  - 0.1
  noise_dataset_selection:
  - 0
  - 1
  - 1
eval:
  eval_on_validation_set: false
  plot_dir: results_plot
  seasonality: 24
dataset:
  data_filename: EUPVGIS_sceaux_2006-2016.csv
  preprocess:
    split_method: datetimes
    split_dates:
    - 01/01/2013
    - 01/01/2014
    num_fourier_terms: 1
    discard_test_year_not_full: true
  parameters:
    dataset_type: pvgis
    rename_columns:
      G(i): radiance
      T2m: temperature
train:
  model:
    name: NARX
    label_columns:
    - radiance
    past_exogenous_columns: null
    future_exogenous_columns: null
    model_params:
      units:
      - 172
      - 79
      delay: 24
      out_steps: 24
      num_features: 1
      exogenous: true
      one_shot_steps: 1
      open_loop_training_mode: true
      activation: relu
      kernel_initializer: he_uniform
      bias_initializer: zeros
      kernel_regularizer: null
      bias_regularizer: null
  next_period_stats:
    next_period_stats:
      use_next_period_stats: false
  batch_size: 512
  output_window_size: 24
  input_window_size: 24
  window_shift: 1
  shuffle: true
  shuffle_buffer_size: 44000
  epochs: 40
  early_stopping: false
  loss:
    name: MeanSquaredError
  optimizer_params:
    learning_rate:
      name: ExponentialDecay
      initial_learning_rate: 0.0004882071614406804
      decay_steps: 120
      decay_rate: 0.9689413359768123
      staircase: false
