base:
  data_dir: data/
  model_dir: trained_models/
  random_seed: 510
calc_daily_stats:
  latitude: 38
  noise_std:
  - 1.5
  - 0.1
  noise_dataset_selection:
  - 0
  - 1
  - 1
eval:
  eval_on_validation_set: false
  plot_dir: results_plot
  seasonality: 24
dataset:
  data_filename: sias_palermo_radiance.csv
  preprocess:
    split_method: datetimes
    split_dates:
    - 01/01/2007
    - 01/01/2008
    num_fourier_terms: 1
  parameters:
    dataset_type: sias
train:
  model:
    name: Lstm
    label_columns:
    - radiance
    past_exogenous_columns:
    - temperature
    future_exogenous_columns: null
    model_params:
      lstm_units:
      - 183
      - 183
      dense_units:
      - 74
      - 74
      num_features: 1
      dropout: 4.965909679695829e-07
      out_steps: 24
      output_activation_function: linear
      output_kernel_initializer: glorot_uniform
      dense_activation: relu
      dense_kernel_initializer: he_uniform
      dense_bias_initializer: zeros
      dense_kernel_regularizer:
        module: keras.regularizers
        class_name: L1L2
        config:
          l1: 0.0005069620624090888
          l2: 0.011799812488690576
      dense_bias_regularizer:
        module: keras.regularizers
        class_name: L1L2
        config:
          l1: 0.010573500227716914
          l2: 0.04751183173683035
  next_period_stats:
    next_period_stats:
      use_next_period_stats: false
  batch_size: 512
  output_window_size: 24
  input_window_size: 24
  window_shift: 1
  shuffle: true
  shuffle_buffer_size: 44000
  epochs: 40
  early_stopping: false
  loss:
    name: MeanSquaredError
  optimizer_params:
    learning_rate:
      name: ExponentialDecay
      initial_learning_rate: 0.0009062522964051312
      decay_steps: 86
      decay_rate: 0.9821234958482601
      staircase: false
