# Example configuration file for generate_plots.py

# Periods to plot line plots
periods_to_plot:
  - start: "2008-02-01"
    end: "2008-02-07"
  - start: "2008-03-01"
    end: "2008-03-07"
  - start: "2008-05-01"
    end: "2008-05-07"
  - start: "2008-07-01"
    end: "2008-07-07"
  - start: "2008-09-01"
    end: "2008-09-07"
  - start: "2008-11-01"
    end: "2008-11-07"

# Experiments to plot
experiments_to_plot:
  M-BiLSTM-ED-sias:
    label: "M-BiLSTM-ED"
    scatter_plot: true
    highlight: true
  M-LSTM-ED-sias:
    label: "M-LSTM-ED"
    scatter_plot: true
    highlight: false
  BiLSTM-ED-sias:
    label: "BiLSTM-ED"
    scatter_plot: false
    highlight: false
  LSTM-ED-sias:
    label: "LSTM-ED"
    scatter_plot: false
    highlight: false
  NARX-sias:
    label: "NARX"
    scatter_plot: false
    highlight: false
  Naive-sias:
    label: "Naive"
    scatter_plot: false
    highlight: false

# extern experiments to plot
extern:
  filename: results_sias_clust-narx.csv
  date_format: "%d-%b-%Y %H:%M:%S"
  label: "Clust+NARX"
  scatter_plot: true
  highlight: true

# Times to plot scatter plots
times_to_plot:
  - "09:00"
  - "12:00"
  - "15:00"

# Seasons for scatter plots
seasons:
  summer:
    - "2008-06-21"
    - "2008-09-20"
  fall:
    - "2008-09-21"
    - "2008-12-20"
  year:
    - "2008-01-01"
    - "2008-12-31"
