defaults:
  - model: deep_next_day_stat
  - next_period_stats: next_period_stats
  - optional model_next_period_stats: ${train/model}

batch_size: 512
output_window_size: 24
input_window_size: 24
window_shift: 24
shuffle: true
shuffle_buffer_size: 44000
epochs: 40
early_stopping: false
loss:
  name: MeanSquaredError
optimizer_params:
  #learning_rate: 1.0e-4
  learning_rate:
    name: ExponentialDecay
    initial_learning_rate: 0.005244
    decay_steps: 10
    decay_rate: 0.955061
    staircase: false
  # learning_rate:
  #   name: CosineDecay
  #   initial_learning_rate: 8.5e-3
  #   decay_steps: 5000
  #   alpha: 1e-5 # as fraction of warmup_target
  #   warmup_steps: 300
  #   warmup_target: 1.2e-2
  