name: BlockLstm
label_columns:
  - radiance
past_exogenous_columns: 
  - temperature
future_exogenous_columns: null

model_params:
  lstm_units: 48
  dense_units:
  - 10
  num_features: 1
  dropout: 0.0
  out_steps: 24
  exogenous: true
  dense_activation: relu
  dense_kernel_initializer: he_uniform
  dense_bias_initializer: zeros
  dense_kernel_regularizer: null
  dense_bias_regularizer: null