name: Lstm
label_columns:
  - radiance
past_exogenous_columns: 
  - temperature
future_exogenous_columns: null

model_params:
  lstm_units:
  - 256
  - 32
  dense_units:
  - 256
  - 32
  num_features: 1
  dropout: 0.0399
  out_steps: 24
  output_activation_function: linear
  output_kernel_initializer: glorot_uniform
  dense_activation: relu
  dense_kernel_initializer: he_uniform
  dense_bias_initializer: zeros
  dense_kernel_regularizer: 
    module: keras.regularizers
    class_name: L1
    config:
      l1: 0.01
  dense_bias_regularizer: null
