name: Lstm
label_columns:
  - radiance
past_exogenous_columns: 
  - temperature
future_exogenous_columns: null

model_params:
  lstm_units:
  - 95
  - 95
  dense_units:
  - 193
  num_features: 1
  use_bidirectional: true
  dropout: 2.4682339393577883e-05
  out_steps: 24
  output_activation_function: linear
  output_kernel_initializer: glorot_uniform
  dense_activation: relu
  dense_kernel_initializer: he_uniform
  dense_bias_initializer: zeros
  dense_kernel_regularizer: 
    module: keras.regularizers
    class_name: L1L2
    config:
      l1: 0.030661006609294352
      l2: 0.022661268066482155
  dense_bias_regularizer:
    module: keras.regularizers
    class_name: L1L2
    config:
      l1:  0.023538661488837667
      l2: 0.06555315893009636
