name: Lstm
label_columns:
  - radiance
past_exogenous_columns: 
  - temperature
future_exogenous_columns: null

model_params:
  lstm_units:
  - 183
  - 183
  dense_units:
  - 74
  - 74
  num_features: 1
  dropout: 4.965909679695829e-07
  out_steps: 24
  output_activation_function: linear
  output_kernel_initializer: glorot_uniform
  dense_activation: relu
  dense_kernel_initializer: he_uniform
  dense_bias_initializer: zeros
  dense_kernel_regularizer: 
    module: keras.regularizers
    class_name: L1L2
    config:
      l1: 0.0005069620624090888
      l2: 0.011799812488690576
  dense_bias_regularizer:
    module: keras.regularizers
    class_name: L1L2
    config:
      l1: 0.010573500227716914
      l2: 0.04751183173683035
