name: Lstm
label_columns:
  - radiance
past_exogenous_columns: 
  - temperature
future_exogenous_columns: null

model_params:
  lstm_units:
  - 136
  - 136
  dense_units:
  - 212
  num_features: 1
  dropout: 1.0809546084968455e-05
  out_steps: 24
  output_activation_function: linear
  output_kernel_initializer: glorot_uniform
  dense_activation: relu
  dense_kernel_initializer: he_uniform
  dense_bias_initializer: zeros
  dense_kernel_regularizer: 
    module: keras.regularizers
    class_name: L1L2
    config:
      l1: 0.00046440678987508255
      l2: 0.08162194306563088
  dense_bias_regularizer:
    module: keras.regularizers
    class_name: L1L2
    config:
      l1: 0.013827531919205617
      l2: 0.09634488694025295
