name: Lstm
label_columns:
  - radiance
past_exogenous_columns: 
  - temperature
future_exogenous_columns: null

model_params:
  lstm_units:
  - 16
  dense_units:
  - 168
  num_features: 1
  use_bidirectional: true
  dropout: 1.763516190129362e-07
  out_steps: 24
  output_activation_function: linear
  output_kernel_initializer: glorot_uniform
  dense_activation: relu
  dense_kernel_initializer: he_uniform
  dense_bias_initializer: zeros
  dense_kernel_regularizer: 
    module: keras.regularizers
    class_name: L1L2
    config:
      l1: 0.007701180752808035
      l2: 0.09101248057486648
  dense_bias_regularizer:
    module: keras.regularizers
    class_name: L1L2
    config:
      l1: 0.018652483037886646
      l2: 0.021403215111720178
