name: NARX
label_columns:
  - radiance
past_exogenous_columns: null
future_exogenous_columns: null
model_params:
  units: 
    - 256
    - 128
  delay: 24
  out_steps: 24
  num_features: 1
  exogenous: true
  one_shot_steps: 1
  open_loop_training_mode: True
  activation: relu
  kernel_initializer: he_uniform
  bias_initializer: zeros
  kernel_regularizer: null
  bias_regularizer: null